modeltype: CondLatentDDPM
modelname: train-Transformer
imagekey: image
data: /gpfs/projects/bsc70/bsc70642/Data/NautilusMRI/train
vae:
  im_channels: 1
  down_channels: 
   - 32
   - 64
   - 128
  mid_channels:
   - 128
  down_sample:
   - True
   - True
  attns: 
   - False
   - False
  z_channels: 8
  n_embed: 512
unet:
  layers_per_block: 3
  block_out_channels: 
    - 256
    - 512
    - 1024
  down_block_types: 
    - DownBlock2D 
    - DownBlock2D 
    - DownBlock2D 
  up_block_types: 
    - UpBlock2D 
    - UpBlock2D 
    - UpBlock2D
scheduler:
  num_train_timesteps: 1000
  beta_schedule: linear
  beta_start: 0.0015
  beta_end: 0.0205
conditioning:
  prev_cond_slices: 2
  post_cond_slices: 0
cond_emb_type: clip
pretraiendVQ_path: /home/bsc/bsc152213/mrigen/VQ-VAE/logs/VQVAE-8-64-64-positional/model/VAE-best-model-parameters-epoch.pt
clip_path: /home/bsc/bsc152213/mrigen/clip-vit-base-patch32
additional:
  encoder_hid_dim: 512
  latent_channels: 8
  image_size: 64