modeltype: Transformer
modelname: train-DiTDiffusion
imagekey: image
data: /gpfs/projects/bsc70/bsc70642/Data/NautilusMRI/train
vae:
  im_channels: 1
  down_channels: 
   - 32
   - 64
   - 128
  mid_channels:
   - 128
  down_sample:
   - True
   - True
  attns: 
   - False
   - False
  z_channels: 8
  n_embed: 512
ditv_params:
  num_layers : 12
  hidden_size : 768
  patch_height : 2
  patch_width : 2
  timestep_emb_dim : 256
  num_heads : 12
  head_dim : 64
scheduler:
  num_train_timesteps: 1000
  beta_schedule: linear
  beta_start: 0.0015
  beta_end: 0.0205
pretraiendVQ_path:  /home/bsc/bsc152213/mrigen/VQ_VAE/logs/VQVAE-8-64-64-positional/model/VAE-best-model-parameters-epoch.pt

